### ISSUE TITLE
Plugin uses XUnit runner 2.x which isn't stable and is causing exceptions

### ISSUE THREAD

**Issue by abatishchev** [rhysgodfrey/team-city-xunit-meta-runner#2]
By some unknown reason plugin stopped working for one of the assemblies in my project throwing an exception:
```
xUnit.net v1 Tests for Project.Server.Api.Test.Integration\bin\Release\Project.Server.Api.Test.Integration.dll (running for 13s)
Project.Server.Api.Test.Integration.Controllers.HomeControllerIntegrationTest.GetRoot_Should_Return_Status_NotFound (running for 13s)
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.

Server stack trace:
 at Xunit.TestClassCallbackHandler.OnTest(XmlNode xml)
 at Xunit.TestClassCallbackHandler.OnXmlNode(XmlNode xml)
 at Xunit.XmlNodeCallbackHandler.System.Web.UI.ICallbackEventHandler.RaiseCallbackEvent(String eventArgument)
 at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
 at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]:
 at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
 at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
 at System.Web.UI.ICallbackEventHandler.RaiseCallbackEvent(String eventArgument)
 --- End of inner exception stack trace ---
 at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
 at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
 at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
 at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
 at Xunit.Sdk.Executor.OnTestResult(ITestResult result, ExecutorCallback callback)
 at Xunit.Sdk.TestClassCommandRunner.Execute(ITestClassCommand testClassCommand, List`1 methods, Predicate`1 startCallback, Predicate`1 resultCallback)
 at Xunit.Sdk.Executor.ThreadRunner(Object threadStart)
 at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
 at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
 at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
 at System.Threading.ThreadHelper.ThreadStart(Object obj)
```
Once I replaced xunit.console.exe ver 2.x with 1.9.x it works just fine.

Can you publish a version of plugin built against the stable version of XUnit, please?

**Comment by abatishchev** [comment]
Any thoughts on this, please?

**Comment by abatishchev** [comment]
Any thoughts on this, please?

**Comment by abatishchev** [comment]
Any thoughts on this, please?

**Comment by abatishchev** [comment]
Any thoughts on this, please?

**Comment by herecydev** [comment]
We've addressed this by upgrading the metarunner in the following repo. Feel free to check that out and report any issues.

https://github.com/4Com/team-city-xunit-meta-runner

**Comment by abatishchev** [comment]
Maybe update to the release? Please.

**Comment by herecydev** [comment]
The  comment  literally above yours addresses that

**Comment by abatishchev** [comment]
So Rhys gave up completely on this project and now you continue working on it?

**Comment by herecydev** [comment]
I don't know what his plans are. We forked his project and have plenty releases that should fulfill what you're after.

**Comment by abatishchev** [comment]
Cool, thanks!
